### PR TITLE
chore: move expo-screen-orientation to peer deps

### PR DESCRIPTION
**Pull request by zhigang1992**

### CODE REVIEW

**Comment by zhigang1992** [comment]
New version of expo-screen-orientation no longer need react-native-unimodules, having it in deps directly doesn't make a lot of sense.

**Comment by petrbela** [comment]
A temporary workaround is to force the upgraded dependency by adding to *your* package.json

```json
  "dependencies": {
    "@expo/match-media": "^0.1.0"
  },
  "resolutions": {
    "expo-screen-orientation": "~4.0.3"
  }
```

**Comment by izakfilmalter** [comment]
Would be great to get this approved and merged.

**Comment by zhigang1992** [comment]
For anyone need this build right now, edit your `package.json` to

```
    "@expo/match-media": "npm:@zhigang1992/match-media@0.1.1",
```

**Pull request merged**
